// Fuente única del FAQ de /planes: la consume <PlanesFaq /> en
// interior-v3/PlanesV3.tsx y el JSON-LD FAQPage de src/app/planes/page.tsx.
export const PLANES_FAQ = [
  { q: "¿Qué es un crédito?", a: "Es la unidad única de consumo de Clinera. En vez de contar conversaciones, agendamientos y llamadas por separado, tienes UNA sola bolsa de créditos que gastas como quieras. Tarifario: una conversación de texto con AURA cuesta 10 créditos, un minuto de voz con CAMILA cuesta 25 créditos, y el agendamiento cuesta 0 (va incluido). La fiscalización de LIA también es gratis; sus informes consumen ~4.000 créditos al mes." },
  { q: "¿Cuántos créditos incluye cada plan?", a: "Vortex: 28.000 créditos/mes (≈2.800 conversaciones · ~400 agendamientos). Atlas: 37.000 créditos/mes (≈2.900 conversaciones · ~320 minutos de voz ≈105 llamadas · ~450 agendamientos). Summit: 46.000 créditos/mes (≈3.100 conversaciones · ~440 minutos de voz ≈145 llamadas · LIA fiscalizando el 100% + informes · ~500 agendamientos). Los equivalentes son estimados con un mix realista; tú decides cómo gastas la bolsa." },
  { q: "¿El agendamiento consume créditos?", a: "No. El agendamiento cuesta 0 créditos: va incluido en la conversación. Solo pagas la conversación con el paciente — el resultado (crear, reagendar o cancelar la cita en tu agenda) no se cobra aparte." },
  { q: "¿Qué incluye la implementación de USD 450?", a: "Es un onboarding asistido por un humano del equipo de Clinera (pago único, no recurrente), no un self-service. Incluye: configuración de AURA con la voz de tu clínica, conexión de tu WhatsApp Business, importación de tu base de pacientes y tratamientos, integración de tu agenda y capacitación de tu equipo. Quedas operando el mismo día. Aplica a los tres planes." },
  { q: "¿Qué pasa si se me acaban los créditos?", a: "Te avisamos al 80% y al 100% de tu bolsa. Tu servicio no se interrumpe sin aviso. Si necesitas más, sumas una recarga de emergencia (USD 20 → 5.000 créditos, ≈500 conversaciones) o subes de plan. La recarga es consumo puntual, no un reemplazo del plan." },
  { q: "¿Cuál es la diferencia entre AURA, CAMILA y LIA?", a: "AURA es el agente de texto: responde, agenda y atiende por WhatsApp 24/7 (en todos los planes). CAMILA es el agente de voz: hace llamadas por ti (desde Atlas). LIA fiscaliza: audita el 100% de las conversaciones, detecta desvíos, reporta y recomienda mejoras con informes diarios y semanales (en Summit)." },
  { q: "¿Puedo elegir el modelo de IA?", a: "Sí. Puedes elegir entre varios modelos de IA (Gemini, Kimi, Claude, GLM, MiniMax, entre otros) según lo que mejor funcione para tu clínica, en cualquiera de los planes." },
  { q: "¿Puedo cambiar de plan después?", a: "Sí. Puedes subir o bajar de plan en cualquier momento desde tu panel. El cambio se aplica en tu próximo ciclo de facturación." },
  { q: "¿Tienen plan para cadenas grandes u hospitales?", a: "Sí, el plan Corporativo (desde USD 1.900/mes) es personalizado: capacidad a medida, onboarding white-glove, SLA personalizado, integraciones a medida, soporte dedicado y facturación adaptada. La implementación se cotiza aparte. Habla con ventas para armar la propuesta." },
  { q: "¿Hay permanencia o contrato?", a: "No. Todos los planes son mes a mes. Puedes cancelar en cualquier momento sin penalizaciones." },
  { q: "¿Se integra con mi software actual?", a: "Sí. Clinera se conecta vía API con Reservo, AgendaPro, Medilink, Dentalink, Sacmed y cualquier sistema que exponga una API REST o soporte MCP." },
  { q: "¿Los precios incluyen IVA?", a: "Los precios están en USD y no incluyen impuestos locales. El monto final depende de la legislación tributaria de tu país." },
];
