// Fuente única del FAQ de /planes: la consume <PlanesFaq /> en
// interior-v3/PlanesV3.tsx y el JSON-LD FAQPage de src/app/planes/page.tsx.
import { VERTEX_IA_MODELS_PROSE } from "@/content/ia-stack";

export const PLANES_FAQ = [
  { q: "¿Qué es un crédito?", a: "Es la unidad única de consumo de Clinera. En vez de contar conversaciones, agendamientos y llamadas por separado, tienes UNA sola bolsa de créditos que gastas como quieras. Tarifario: una conversación de texto con AURA que no termina en cita cuesta ~30 créditos, un minuto de voz con CAMILA cuesta 25 créditos, y un agendamiento automático (la IA agenda sola) cuesta ~195 créditos: más que una conversación normal, porque la IA razona, consulta tu agenda en tiempo real y ejecuta varios pasos. La fiscalización de LIA también es gratis; sus informes consumen ~4.000 créditos al mes." },
  { q: "¿Cuántos créditos incluye cada plan?", a: "Vortex: 28.000 créditos/mes (≈933 conversaciones de texto o ~143 agendamientos automáticos). Atlas: 37.000 créditos/mes (≈1.233 conversaciones o ~189 agendamientos, o repártelos con la voz de CAMILA). Summit: 46.000 créditos/mes (≈1.533 conversaciones o ~235 agendamientos, o repártelos con voz y LIA fiscalizando). Una conversación sale a ~30 créditos (créditos ÷ 30) y un agendamiento automático a ~195; como es una sola bolsa, tú decides cómo la mezclas." },
  { q: "¿El agendamiento consume créditos?", a: "Sí. Clinera opera en un único modo, Agentic: la IA agenda sola dentro del chat. Una conversación completa de agendamiento consume ~195 créditos, bastante más que una conversación que solo informa (~30), porque la IA razona, consulta la disponibilidad real de tu agenda y ejecuta varios pasos para crear, reagendar o cancelar la cita. Todo se descuenta de la misma bolsa." },
  { q: "¿Qué incluye el costo de configuración de USD 450?", a: "Es un pago único (no recurrente) de onboarding asistido por un humano del equipo de Clinera, no un self-service. Incluye: migración de tus fichas clínicas y datos históricos, migración de pacientes y tratamientos, configuración y entrenamiento de tus agentes de IA con la voz de tu clínica, conexión de tu WhatsApp Business, integración de tu agenda y capacitación de tu equipo. Quedas operando el mismo día. Se cobra sólo en la modalidad mensual (el plan arranca después de la implementación). En semestral y anual la implementación va incluida sin costo y el plan se cobra de inmediato." },
  { q: "¿Qué pasa si se me acaban los créditos?", a: "Te avisamos al 80% y al 100% de tu bolsa. Tu servicio no se interrumpe sin aviso. Si necesitas más, sumas una recarga de emergencia (USD 15 → 5.000 créditos, ≈166 conversaciones o ~25 agendamientos) o subes de plan. La recarga es consumo puntual, no un reemplazo del plan." },
  { q: "¿Cuál es la diferencia entre AURA, CAMILA y LIA?", a: "Las tres están disponibles hoy. AURA es el empleado digital de texto: responde, agenda y atiende por WhatsApp 24/7 (todos los planes). CAMILA es el empleado digital de voz: llama para confirmar y reagendar (desde Atlas, 25 créditos por minuto). LIA es la orquestadora: fiscaliza la operación en Summit (fiscalización 0 créditos; informes ≈4.000 créditos/mes)." },
  { q: "¿Puedo elegir el modelo de IA?", a: `Clinera opera con ${VERTEX_IA_MODELS_PROSE} en Vertex AI (Google Cloud) y selecciona el modelo óptimo por tarea. No hay selección manual de modelos por el usuario: el stack está fijado para que la IA ejecute con consistencia en todos los planes.` },
  { q: "¿Puedo cambiar de plan después?", a: "Sí. Puedes subir o bajar de plan en cualquier momento desde tu panel. El cambio se aplica en tu próximo ciclo de facturación." },
  { q: "¿Tienen plan para cadenas grandes u hospitales?", a: "Los planes publicados llegan hasta Summit (USD 479/mes): 46.000 créditos, 25 usuarios y sucursales ilimitadas, con AURA, CAMILA y LIA. Si tu cadena necesita algo fuera de ese marco, habla con ventas para evaluar el alcance." },
  { q: "¿Cuáles son las modalidades de pago?", a: "Hay tres. Anual: pagas los 12 meses por adelantado con 20% de descuento y la implementación de USD 450 va gratis (Vortex USD 2.678/año ≈ USD 223,17/mes, Atlas USD 3.638/año ≈ USD 303,17/mes, Summit USD 4.598/año ≈ USD 383,17/mes). Semestral: pagas 6 meses por adelantado con 20% de descuento e implementación gratis (Vortex USD 1.339,20, Atlas USD 1.819,20, Summit USD 2.299,20). Mensual: pagas la implementación de USD 450 al inicio y el plan mes a mes a precio de lista (USD 279 / 379 / 479) después. Semestral y anual son las modalidades recomendadas: implementación gratis y el plan se cobra de inmediato." },
  { q: "¿Hay permanencia o contrato?", a: "Sí. Todos los planes tienen una permanencia mínima de 6 meses. Puedes pagar mes a mes (con implementación cobrada al inicio), anticipar el semestre con 20% de descuento e implementación gratis, o anticipar el año con 20% de descuento e implementación gratis." },
  { q: "¿Se integra con mi software actual?", a: "No. Clinera no se conecta a sistemas de agenda externos: opera sobre su propia agenda, sus propias fichas clínicas y su propio módulo de pagos. Por eso la IA puede agendar sola dentro del chat, sin mandar links ni depender de la disponibilidad de un tercero. En el onboarding migramos tus pacientes, tratamientos y datos históricos desde tu sistema actual para que partas con todo cargado." },
  { q: "¿Los precios incluyen IVA?", a: "Los precios están en USD y no incluyen impuestos locales. El monto final depende de la legislación tributaria de tu país." },
];
